# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: Npm install
  inputs:
    command: 'install'
    workingDir: 'Ionic'

- task: CmdLine@2
  displayName: Cordova Install
  inputs:
    script: 'npm i -g cordova-res'

- task: IonicCommand@1
  displayName: Resources
  inputs:
    ionicCommand: 'cordova resources'
    ionicVersion: '5.2.3'
    cordovaVersion: '7.1.0'
    cwd: 'Ionic'

- task: IonicCommand@1
  displayName: Prepare
  inputs:
    ionicCommand: 'cordova prepare'
    ionicArgs: '--reset'
    ionicVersion: '5.2.3'
    cordovaVersion: '7.1.0'
    cwd: 'Ionic'
    
- task: IonicCommand@1
  displayName: Build Android Release
  inputs:
    ionicCommand: 'build android --release'
    ionicVersion: '5.2.3'
    cordovaVersion: '7.1.0'
    cwd: 'Ionic'